// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceMarketplace.Data;

#nullable disable

namespace ServiceMarketplace.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260111214538_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceMarketplace.Models.AdminPriceReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("RegionModifier")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminPriceReferences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 850m,
                            Brand = "Fawori",
                            Category = "Boya",
                            IsActive = true,
                            MaterialName = "İç Cephe Duvar Boyası",
                            Quality = "Standart",
                            Quantity = 15m,
                            RegionModifier = 1.0,
                            Unit = "Litre"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 1200m,
                            Brand = "Marshall",
                            Category = "Boya",
                            IsActive = true,
                            MaterialName = "İç Cephe Duvar Boyası",
                            Quality = "Premium",
                            Quantity = 15m,
                            RegionModifier = 1.0,
                            Unit = "Litre"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 450m,
                            Brand = "Marshall",
                            Category = "Boya",
                            IsActive = true,
                            MaterialName = "Astar",
                            Quality = "Standart",
                            Quantity = 15m,
                            RegionModifier = 1.0,
                            Unit = "Litre"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 180m,
                            Brand = "Ege Seramik",
                            Category = "Seramik",
                            IsActive = true,
                            MaterialName = "Yer Seramiği 60x60",
                            Quality = "Premium",
                            Quantity = 1m,
                            RegionModifier = 1.0,
                            Unit = "m²"
                        });
                });

            modelBuilder.Entity("ServiceMarketplace.Models.ListingCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstimatedDaysMax")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedDaysMin")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedLaborMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedLaborMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedMaterialMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedMaterialMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<double>("RequiredCeramic")
                        .HasColumnType("float");

                    b.Property<double>("RequiredPaint")
                        .HasColumnType("float");

                    b.Property<double>("RequiredPrimer")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ListingCalculations");
                });

            modelBuilder.Entity("ServiceMarketplace.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalServicesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedDays")
                        .HasColumnType("int");

                    b.Property<decimal>("LaborCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LaborCostType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaterialCostTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaterialSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalOfferPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("ServiceMarketplace.Models.OfferMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminPriceId")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.ToTable("OfferMaterials");
                });

            modelBuilder.Entity("ServiceMarketplace.Models.OfferMaterial", b =>
                {
                    b.HasOne("ServiceMarketplace.Models.Offer", "Offer")
                        .WithMany("Materials")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("ServiceMarketplace.Models.Offer", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
